language: java

# use Java 8 for the build
jdk:
  - oraclejdk8

# use of container-based infrastructure
sudo: false

cache:
  directories:
    $HOME/.m2

script:
  - mvn install

# exclude the `master` from Travis CI builds, as
# it is status-check protected and will only accept
# commits that passed a `mvn install` run on Travis
branches:
  except:
  - master