highlighter:        rouge

title:              Peel Framework

current_version:    1.0.0-rc7

collections:
  manual:
    output:         true
  repository:
    output:         true
  legal:
    output:         true
