highlighter:        pygments

title:              Peel Framework<sup>beta</sup>

current_version:    1.0-SNAPSHOT

collections:
  manual:
    output:         true
  repository:
    output:         true
  legal:
    output:         true