highlighter:        rouge

title:              Peel Framework<sup>beta</sup>

current_version:    1.0.0-rc2

collections:
  manual:
    output:         true
  repository:
    output:         true
  legal:
    output:         true
